# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
host: 0.0.0.0
title: HackBrexit
email: eddie@jaoudestudios.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hackbrexit.github.io" # the base hostname & protocol for your site
twitter_username: hackbrexit
github_username:  hackbrexit

# Build settings
markdown: kramdown
